version: '3.7'
services:
  blog:
    # build: .
    image: jekyll/jekyll:latest
    container_name: web
    ports:
      - 4000:4000/tcp
    volumes:
      - ./:/srv/jekyll
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve
    networks:
      front:


networks:
  front:
    driver: bridge
