version: '3.7'
services:
  blog:
    restart: always
    # build: .
    # image: jekyll/jekyll:latest
    image: mengbin92/jekyll:4.3.2
    container_name: web
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/jekyll
    command: jekyll serve -H 0.0.0.0
    networks:
      front:


networks:
  front:
    driver: bridge
