services:
  gobin-build:
    image: docker.io/mengbin92/gobin:v1.2.0
    container_name: blog-gobin-build
    working_dir: /site
    volumes:
      - ./:/site
    command: gobin build --minify
    profiles:
      - build

  web:
    restart: always
    image: nginx:alpine
    container_name: blog-web
    ports:
      - "18595:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
