version: '3.7'
services:
  blog:
    # build: .
    image: jekyll/jekyll:latest
    ports:
      - 4000:4000/tcp
    volumes:
      - ./:/srv/jekyll
    environment:
      - JEKYLL_ENV=docker
    command: bundle exec jekyll serve
    networks:
      front:

networks:
  front:
    driver: bridge