version: '3.7'
services:
  blog:
    restart: always
    # build: .
    image: mengbin92/jekyll:4.3.2
    container_name: blog
    volumes:
      - ./:/srv/jekyll
    command: jekyll serve
    networks:
      front:
  
  web:
    image: nginx:alpine3.18
    container_name: web
    ports:
      - 4000:80
    volumes:
      - ./_site:/usr/share/nginx/html
    depends_on:
      - blog
    networks:
      front:


networks:
  front:
    driver: bridge
